INSERT INTO PRODUTO (NOME, PRECO, DESCRICAO, QUANTIDADE, CATEGORIA) VALUES
('Notebook Gamer X', 5999.99, 'Notebook potente para jogos', 10, 'Eletrônicos'),
('Smartphone Ultra Y', 2999.90, 'Celular com câmera de 108MP', 15, 'Eletrônicos'),
('Fone Bluetooth Pro', 499.99, 'Fone sem fio com cancelamento de ruído', 50, 'Acessórios'),
('TV 4K 55" Samsung', 3999.00, 'Smart TV 4K UHD', 5, 'Eletrônicos'),
('Cadeira Gamer Z', 899.90, 'Cadeira ergonômica para jogos', 8, 'Móveis'),
('Mouse Óptico X200', 149.99, 'Mouse gamer com RGB', 30, 'Acessórios'),
('Teclado Mecânico Y', 299.99, 'Teclado mecânico switch vermelho', 25, 'Acessórios'),
('Monitor 27" 144Hz', 1899.99, 'Monitor gamer 144Hz 1ms', 12, 'Eletrônicos'),
('Impressora Multifuncional', 799.90, 'Impressora jato de tinta', 7, 'Eletrônicos'),
('Roteador Wi-Fi 6', 599.99, 'Roteador gigabit com Wi-Fi 6', 20, 'Eletrônicos'),

('Cafeteira Elétrica', 249.99, 'Prepara café automaticamente', 15, 'Eletrodomésticos'),
('Microondas 30L', 499.99, 'Microondas digital 30 litros', 10, 'Eletrodomésticos'),
('Aspirador de Pó Turbo', 399.99, 'Alta potência e baixo consumo', 5, 'Eletrodomésticos'),
('Ar Condicionado Split 12K', 2399.99, 'Ar condicionado inverter', 6, 'Eletrodomésticos'),
('Geladeira Frost Free', 3899.99, 'Geladeira com tecnologia Frost Free', 4, 'Eletrodomésticos'),

('Bicicleta Speed Pro', 3999.99, 'Bicicleta profissional para estrada', 3, 'Esportes'),
('Esteira Ergométrica X', 2799.99, 'Esteira dobrável com visor digital', 4, 'Esportes'),
('Relógio Smart Fitness', 399.99, 'Smartwatch com monitor cardíaco', 20, 'Esportes'),
('Kit Halteres 20Kg', 299.99, 'Halteres ajustáveis para musculação', 10, 'Esportes'),
('Mochila Tática 40L', 199.99, 'Mochila resistente para trilhas', 12, 'Esportes'),

('Livro: Inteligência Artificial', 89.99, 'Livro sobre IA e aprendizado de máquina', 30, 'Livros'),
('Livro: Programação Python', 79.99, 'Curso completo de Python', 25, 'Livros'),
('Livro: Design Gráfico', 69.99, 'Técnicas para design digital', 18, 'Livros'),
('Livro: História do Brasil', 49.99, 'Livro didático sobre história brasileira', 20, 'Livros'),
('Livro: Marketing Digital', 59.99, 'Guia prático de marketing online', 15, 'Livros'),

('Tênis Esportivo X', 399.99, 'Tênis confortável para corridas', 12, 'Moda'),
('Camisa Social Premium', 199.99, 'Camisa 100% algodão', 30, 'Moda'),
('Jaqueta de Couro Z', 499.99, 'Jaqueta de couro legítimo', 8, 'Moda'),
('Bolsa Feminina Luxo', 299.99, 'Bolsa de couro elegante', 10, 'Moda'),
('Óculos de Sol Polarizado', 149.99, 'Óculos com proteção UV', 20, 'Moda'),

('Console Gamer X', 4499.99, 'Videogame de última geração', 5, 'Eletrônicos'),
('Drone Profissional', 2999.99, 'Drone com câmera 4K', 6, 'Eletrônicos'),
('Caixa de Som Bluetooth', 499.99, 'Caixa portátil potente', 15, 'Eletrônicos'),
('Carregador Portátil 10.000mAh', 99.99, 'Power bank para celulares', 30, 'Acessórios'),
('Câmera Profissional DSLR', 5999.99, 'Câmera para fotografia profissional', 4, 'Eletrônicos'),

('Fogão 5 Bocas', 1899.99, 'Fogão a gás com acendimento automático', 7, 'Eletrodomésticos'),
('Liquidificador 1.5L', 199.99, 'Liquidificador potente', 15, 'Eletrodomésticos'),
('Ventilador de Mesa', 129.99, 'Ventilador silencioso', 25, 'Eletrodomésticos'),
('Forno Elétrico 50L', 599.99, 'Forno com timer digital', 10, 'Eletrodomésticos'),
('Máquina de Lavar 12kg', 2499.99, 'Lavadora automática', 6, 'Eletrodomésticos'),

('Bola de Futebol Oficial', 199.99, 'Bola padrão FIFA', 20, 'Esportes'),
('Raquete de Tênis Pro', 799.99, 'Raquete profissional leve', 10, 'Esportes'),
('Corda de Pular Speed', 49.99, 'Corda ajustável para treinos', 30, 'Esportes'),
('Coqueteleira 600ml', 39.99, 'Shaker para suplementos', 40, 'Esportes'),
('Suplemento Whey Protein', 199.99, 'Proteína para ganho muscular', 15, 'Esportes'),

('Chuteira de Futebol', 349.99, 'Chuteira para gramado natural', 12, 'Moda'),
('Mochila Escolar', 149.99, 'Mochila resistente para notebooks', 18, 'Moda'),
('Relógio de Pulso Clássico', 499.99, 'Relógio masculino sofisticado', 10, 'Moda'),
('Brinco de Prata', 79.99, 'Brinco elegante feminino', 25, 'Moda'),
('Pulseira de Ouro', 899.99, 'Pulseira 18K', 5, 'Moda'),

('Tablet 10" Full HD', 1999.99, 'Tablet para estudo e trabalho', 8, 'Eletrônicos'),
('Kindle Paperwhite', 799.99, 'Leitor digital de e-books', 12, 'Eletrônicos'),
('Suporte para Notebook', 129.99, 'Suporte ajustável ergonômico', 30, 'Acessórios'),
('Cadeira de Escritório', 699.99, 'Cadeira ergonômica com ajuste de altura', 10, 'Móveis'),
('Escrivaninha Compacta', 399.99, 'Mesa de trabalho moderna', 8, 'Móveis');
